name: pickled_cucumber
description: A simple cucumber implementation for Dart, Dart Frog and Flutter.
version: 1.0.6
repository: https://github.com/PiotrFLEURY/pickled_cucumber

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  file: ^7.0.0
  test: ^1.24.0
  source_gen: ^1.4.0

dev_dependencies:
  lints: ^4.0.0
